//! Order CSS properties the way Recess did and Bootstrap does.
//! A port of https://github.com/stormwarning/stylelint-config-recess-order

/// CSS property order following the Recess/stylelint-config-recess-order standard.
/// Properties are organized in logical groups based on their specification module.
pub const PROPERTY_ORDER: &[&str] = &[
	// Compose rules from other selectors in CSS Modules
	// https://github.com/css-modules/css-modules#composition
	"composes",
	// Cascade and inheritance
	"all",
	// Positioned layout
	"position",
	"inset",
	"inset-block",
	"inset-block-start",
	"inset-block-end",
	"inset-inline",
	"inset-inline-start",
	"inset-inline-end",
	"top",
	"right",
	"bottom",
	"left",
	"z-index",
	"float",
	"clear",
	// Display
	"box-sizing",
	"display",
	"visibility",
	// Flexible box layout
	"flex",
	"flex-grow",
	"flex-shrink",
	"flex-basis",
	"flex-flow",
	"flex-direction",
	"flex-wrap",
	"-webkit-box-orient",
	// Grid layout
	"grid",
	"grid-area",
	"grid-template",
	"grid-template-areas",
	"grid-template-rows",
	"grid-template-columns",
	"grid-row",
	"grid-row-start",
	"grid-row-end",
	"grid-column",
	"grid-column-start",
	"grid-column-end",
	"grid-auto-rows",
	"grid-auto-columns",
	"grid-auto-flow",
	"grid-gap",
	"grid-row-gap",
	"grid-column-gap",
	// Box alignment (Flexbox and Grid)
	"gap",
	"row-gap",
	"column-gap",
	"place-content",
	"place-items",
	"place-self",
	"align-content",
	"align-items",
	"align-self",
	"justify-content",
	"justify-items",
	"justify-self",
	// Order
	"order",
	// Box sizing
	"inline-size",
	"min-inline-size",
	"max-inline-size",
	"width",
	"min-width",
	"max-width",
	"block-size",
	"min-block-size",
	"max-block-size",
	"height",
	"min-height",
	"max-height",
	"aspect-ratio",
	"contain-intrinsic-inline-size",
	"contain-intrinsic-block-size",
	"contain-intrinsic-size",
	"contain-intrinsic-width",
	"contain-intrinsic-height",
	// Box model
	"padding",
	"padding-block",
	"padding-block-start",
	"padding-block-end",
	"padding-inline",
	"padding-inline-start",
	"padding-inline-end",
	"padding-top",
	"padding-right",
	"padding-bottom",
	"padding-left",
	"margin",
	"margin-block",
	"margin-block-start",
	"margin-block-end",
	"margin-inline",
	"margin-inline-start",
	"margin-inline-end",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	// Containment
	"contain",
	"container",
	"container-name",
	"container-type",
	"content-visibility",
	// Overflow
	"overflow",
	"overflow-inline",
	"overflow-block",
	"overflow-x",
	"overflow-y",
	"scrollbar-gutter",
	"-webkit-overflow-scrolling",
	"-ms-overflow-x",
	"-ms-overflow-y",
	"-ms-overflow-style",
	"text-overflow",
	"-webkit-line-clamp",
	"line-clamp",
	"scroll-behaviour",
	// Overscroll behavior
	"overscroll-behavior",
	"overscroll-behavior-inline",
	"overscroll-behavior-block",
	"overscroll-behavior-x",
	"overscroll-behavior-y",
	// Fonts
	"font",
	"font-family",
	"font-size",
	"font-size-adjust",
	"font-variation-settings",
	"font-style",
	"font-weight",
	"font-optical-sizing",
	"font-stretch",
	"font-feature-settings",
	"font-kerning",
	"font-variant",
	"font-variant-ligatures",
	"font-variant-caps",
	"font-variant-alternates",
	"font-variant-numeric",
	"font-variant-east-asian",
	"font-variant-position",
	"-webkit-font-smoothing",
	"-moz-osx-font-smoothing",
	"font-smooth",
	"font-synthesis",
	"font-synthesis-weight",
	"font-synthesis-style",
	"font-synthesis-small-caps",
	// Inline layout
	"line-height",
	"vertical-align",
	"alignment-baseline",
	"baseline-shift",
	"dominant-baseline",
	// Colors
	"base-palette",
	"override-colors",
	"font-palette",
	"color",
	"-webkit-text-fill-color",
	"-webkit-text-stroke",
	"-webkit-text-stroke-width",
	"-webkit-text-stroke-color",
	// Text
	"text-align",
	"text-align-last",
	"text-justify",
	"text-indent",
	"text-transform",
	"word-spacing",
	"letter-spacing",
	"hyphens",
	"hyphenate-character",
	"line-break",
	"word-break",
	"text-wrap",
	"text-wrap-mode",
	"text-wrap-style",
	"word-wrap",
	"overflow-wrap",
	"tab-size",
	"white-space",
	"white-space-collapse",
	// Text decoration
	"text-emphasis",
	"text-emphasis-color",
	"text-emphasis-style",
	"text-emphasis-position",
	"text-decoration",
	"text-decoration-line",
	"text-decoration-thickness",
	"text-decoration-style",
	"text-decoration-color",
	"text-decoration-skip-ink",
	"text-underline-position",
	"text-underline-offset",
	"text-shadow",
	// Ruby layout
	"ruby-position",
	"ruby-align",
	// Font loading
	"src",
	"font-display",
	"unicode-range",
	"size-adjust",
	"ascent-override",
	"descent-override",
	"line-gap-override",
	// Basic user interface
	"appearance",
	"accent-color",
	"pointer-events",
	"-ms-touch-action",
	"touch-action",
	"cursor",
	"caret-color",
	"zoom",
	"resize",
	"user-select",
	"-webkit-user-select",
	"nav-index",
	"nav-up",
	"nav-right",
	"nav-down",
	"nav-left",
	"outline",
	"outline-width",
	"outline-style",
	"outline-color",
	"outline-offset",
	// Color adjustment
	"color-scheme",
	"forced-color-adjust",
	"print-color-adjust",
	// Table
	"table-layout",
	"empty-cells",
	"caption-side",
	"border-spacing",
	"border-collapse",
	// Generated content
	"content",
	"quotes",
	// Lists and counters
	"list-style",
	"list-style-position",
	"list-style-type",
	"list-style-image",
	"counter-reset",
	"counter-set",
	"counter-increment",
	// Scroll snap
	"scroll-snap-type",
	"scroll-snap-align",
	"scroll-snap-stop",
	"scroll-padding",
	"scroll-padding-block",
	"scroll-padding-block-start",
	"scroll-padding-block-end",
	"scroll-padding-inline",
	"scroll-padding-inline-start",
	"scroll-padding-inline-end",
	"scroll-padding-top",
	"scroll-padding-right",
	"scroll-padding-bottom",
	"scroll-padding-left",
	"scroll-margin",
	"scroll-margin-block",
	"scroll-margin-block-start",
	"scroll-margin-block-end",
	"scroll-margin-inline",
	"scroll-margin-inline-start",
	"scroll-margin-inline-end",
	"scroll-margin-top",
	"scroll-margin-right",
	"scroll-margin-bottom",
	"scroll-margin-left",
	// Scrollbars styling
	"scrollbar-color",
	"scrollbar-width",
	// Images
	"object-fit",
	"object-position",
	"-ms-interpolation-mode",
	"image-orientation",
	"image-rendering",
	"image-resolution",
	// Backgrounds and borders
	"background",
	"background-color",
	"background-image",
	"filter:progid:DXImageTransform.Microsoft.gradient",
	"background-repeat",
	"background-attachment",
	"background-position",
	"background-position-x",
	"background-position-y",
	"background-clip",
	"background-origin",
	"background-size",
	"border",
	"border-color",
	"border-style",
	"border-width",
	"border-block",
	"border-block-start",
	"border-block-start-color",
	"border-block-start-style",
	"border-block-start-width",
	"border-block-end",
	"border-block-end-color",
	"border-block-end-style",
	"border-block-end-width",
	"border-inline",
	"border-inline-start",
	"border-inline-start-color",
	"border-inline-start-style",
	"border-inline-start-width",
	"border-inline-end",
	"border-inline-end-color",
	"border-inline-end-style",
	"border-inline-end-width",
	"border-top",
	"border-top-color",
	"border-top-style",
	"border-top-width",
	"border-right",
	"border-right-color",
	"border-right-style",
	"border-right-width",
	"border-bottom",
	"border-bottom-color",
	"border-bottom-style",
	"border-bottom-width",
	"border-left",
	"border-left-color",
	"border-left-style",
	"border-left-width",
	"border-radius",
	"border-start-start-radius",
	"border-start-end-radius",
	"border-end-start-radius",
	"border-end-end-radius",
	"border-top-left-radius",
	"border-top-right-radius",
	"border-bottom-right-radius",
	"border-bottom-left-radius",
	"border-image",
	"border-image-source",
	"border-image-slice",
	"border-image-width",
	"border-image-outset",
	"border-image-repeat",
	"box-shadow",
	// Compositing and blending
	"background-blend-mode",
	"isolation",
	"mix-blend-mode",
	"opacity",
	// Filter effects
	"filter",
	"backdrop-filter",
	// Masking
	"clip",
	"clip-path",
	"clip-rule",
	"mask-border",
	"mask-border-source",
	"mask-border-slice",
	"mask-border-width",
	"mask-border-outset",
	"mask-border-repeat",
	"mask-border-mode",
	"mask",
	"mask-image",
	"mask-mode",
	"mask-repeat",
	"mask-position",
	"mask-clip",
	"mask-origin",
	"mask-size",
	"mask-composite",
	"mask-type",
	// Shapes
	"shape-outside",
	"shape-image-threshold",
	"shape-margin",
	// Writing modes
	"direction",
	"unicode-bidi",
	"writing-mode",
	"text-orientation",
	"text-combine-upright",
	// SVG presentation attributes
	"text-anchor",
	"fill",
	"fill-rule",
	"fill-opacity",
	"stroke",
	"stroke-opacity",
	"stroke-width",
	"stroke-linecap",
	"stroke-linejoin",
	"stroke-miterlimit",
	"stroke-dasharray",
	"stroke-dashoffset",
	"color-interpolation",
	"color-interpolation-filters",
	"flood-color",
	"flood-opacity",
	"lighting-color",
	"marker",
	"marker-start",
	"marker-mid",
	"marker-end",
	"stop-color",
	"stop-opacity",
	"paint-order",
	"shape-rendering",
	"text-rendering",
	// Transforms
	"transform",
	"transform-origin",
	"transform-box",
	"transform-style",
	"rotate",
	"scale",
	"translate",
	"perspective",
	"perspective-origin",
	"backface-visibility",
	// Transitions
	"transition",
	"transition-delay",
	"transition-timing-function",
	"transition-duration",
	"transition-property",
	// View transitions
	"view-transition-name",
	"view-transition-class",
	// Animations
	"animation",
	"animation-name",
	"animation-duration",
	"animation-timing-function",
	"animation-delay",
	"animation-iteration-count",
	"animation-direction",
	"animation-fill-mode",
	"animation-play-state",
	"animation-composition",
	// Motion path
	"offset",
	"offset-position",
	"offset-path",
	"offset-distance",
	"offset-rotate",
	"offset-anchor",
	// Will change
	"will-change",
	// Fragmentation
	"break-before",
	"break-after",
	"break-inside",
	"widows",
	"orphans",
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_property_order_not_empty() {
		assert!(!PROPERTY_ORDER.is_empty());
	}

	#[test]
	fn test_no_duplicates() {
		let mut sorted = PROPERTY_ORDER.to_vec();
		sorted.sort();
		sorted.dedup();
		assert_eq!(
			sorted.len(),
			PROPERTY_ORDER.len(),
			"PROPERTY_ORDER contains duplicates"
		);
	}

	#[test]
	fn test_contains_positioning() {
		assert!(PROPERTY_ORDER.contains(&"position"));
		assert!(PROPERTY_ORDER.contains(&"top"));
		assert!(PROPERTY_ORDER.contains(&"z-index"));
	}

	#[test]
	fn test_contains_display() {
		assert!(PROPERTY_ORDER.contains(&"display"));
		assert!(PROPERTY_ORDER.contains(&"flex-direction"));
		assert!(PROPERTY_ORDER.contains(&"grid"));
	}

	#[test]
	fn test_contains_box_model() {
		assert!(PROPERTY_ORDER.contains(&"width"));
		assert!(PROPERTY_ORDER.contains(&"height"));
		assert!(PROPERTY_ORDER.contains(&"margin"));
		assert!(PROPERTY_ORDER.contains(&"padding"));
	}

	#[test]
	fn test_composes_first() {
		assert_eq!(PROPERTY_ORDER[0], "composes");
	}

	#[test]
	fn test_all_second() {
		assert_eq!(PROPERTY_ORDER[1], "all");
	}
}
